## Descriptions
F1-score for each class using best model.

In [12]:
from functools import partial

import numpy as np
import pandas as pd
import tensorflow as tf

import seaborn as sns
import matplotlib.pyplot as plt

from modules.dataset import Dataset, LABELS

In [13]:
!pip3 install tensorflow_addons
import tensorflow_addons as tfa

Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com


In [14]:
sns.set_theme()

## Best Model

In [4]:
class Evaluate:
    def __init__(self, model_path):
        self.y_true = None
        self.y_preds = None
        self.model_path = model_path
        self.model = self.get_model(model_path)
        self.best_thresholds = None
        self.thresholds_200 = None
    
    def get_model(self, path):
        return tf.keras.models.load_model(path)
    
    def get_y_true(self, data):
        y_true=[]
        for X,y in data:
            for label in y:
                y_true.append(label)
        y_true = tf.Variable(y_true)
        self.y_true = y_true
        return y_true

    def get_confusion_metrics(self, y_true, y_preds):
        m = tf.keras.metrics.AUC(multi_label=True)
        m.update_state(y_true, y_preds)

        thresholds = m.thresholds
        variables = m.variables
        TP = variables[0]
        TN = variables[1]
        FP = variables[2]
        FN = variables[3]
        return thresholds, TP, TN, FP, FN

    def model_predict(self, test_dataset):
        return self.model.predict(test_dataset)

    def get_f1_scores_200_thresholds(self, test_dataset):
        self.y_true = self.get_y_true(test_dataset)
        self.y_preds = self.model_predict(test_dataset)
        
        confusion_metrics = self.get_confusion_metrics(self.y_true, self.y_preds)
        thresholds, TP, TN, FP, FN = confusion_metrics
        self.thresholds_200 = thresholds
        f1_class_dict = dict()
        for i in range(len(thresholds)):
            tp, tn, fp, fn = TP[i], TN[i], FP[i], FN[i]
            for label_index in range(15):
                f1_score = 2*tp[label_index] / (2*tp[label_index] + fp[label_index] + fn[label_index])
                try:
                    f1_class_dict[LABELS[label_index]].append(f1_score)
                except KeyError:
                    f1_class_dict[LABELS[label_index]] = [f1_score]
        print(LABELS)
        return f1_class_dict
    
    def get_f1_scores(self, test_dataset):
        self.y_true = self.get_y_true(test_dataset)
        self.y_preds = self.model_predict(test_dataset)
        metric = tfa.metrics.MultiLabelConfusionMatrix(num_classes=15)
        metric.update_state(self.y_true,
                            np.greater_equal(self.y_preds, self.best_thresholds).astype('int8'))
        result = metric.result()
        
        f1_class_dict = dict()
        for idx, confusion in enumerate(result):
            label = LABELS[idx]
            TP, TN, FP, FN = (confusion[1, 1],
                              confusion[0, 0],
                              confusion[0, 1],
                              confusion[1, 0])
            f1_score = 2*TP / (2*TP + FP + FN)
            f1_class_dict[label] = [f1_score.numpy()]
        return f1_class_dict
    
    def get_precision_scores(self, test_dataset, new_calculate=True):
        if new_calculate is True:
            self.y_true = self.get_y_true(test_dataset)
            self.y_preds = self.model_predict(test_dataset)
        metric = tfa.metrics.MultiLabelConfusionMatrix(num_classes=15)
        metric.update_state(self.y_true,
                            np.greater_equal(self.y_preds, self.best_thresholds).astype('int8'))
        result = metric.result()
        
        precision_class_dict = dict()
        for idx, confusion in enumerate(result):
            label = LABELS[idx]
            TP, TN, FP, FN = (confusion[1, 1],
                              confusion[0, 0],
                              confusion[0, 1],
                              confusion[1, 0])
            precision = TP / (TP + FP)
            precision_class_dict[label] = [precision.numpy()]
        return precision_class_dict
    
    def get_recall_scores(self, test_dataset, new_calculate=True):
        if new_calculate is True:
            self.y_true = self.get_y_true(test_dataset)
            self.y_preds = self.model_predict(test_dataset)
        metric = tfa.metrics.MultiLabelConfusionMatrix(num_classes=15)
        metric.update_state(self.y_true,
                            np.greater_equal(self.y_preds, self.best_thresholds).astype('int8'))
        result = metric.result()
        
        recall_class_dict = dict()
        for idx, confusion in enumerate(result):
            label = LABELS[idx]
            TP, TN, FP, FN = (confusion[1, 1],
                              confusion[0, 0],
                              confusion[0, 1],
                              confusion[1, 0])
            recall = TP / (TP + FN)
            recall_class_dict[label] = [recall.numpy()]
        return recall_class_dict
    
    def get_best_threshold(self):
        fold_num = int(self.model_path.split(".")[0][-1])
        test_dataset = datasets[fold_num-1]
        f1_scores_dict = self.get_f1_scores_200_thresholds(test_dataset)
        best_thresholds_dict = {"thresholds": [], "f1_most": [], "label": []}
        for key, value in f1_scores_dict.items():
            f1_arg_max = np.argmax(value)
            best_thresholds_dict["f1_most"].append(value[f1_arg_max].numpy())
            best_thresholds_dict["label"].append(key)
            best_thresholds_dict["thresholds"].append(self.thresholds_200[f1_arg_max])
        
        df = pd.DataFrame(best_thresholds_dict)
        df = df.set_index("label")
        print(df)
        
        df_200_thresholds = pd.DataFrame(f1_scores_dict)
        
        df_200_thresholds.to_csv("/home/jovyan/ChestXray-14/results/paper/table3_1/f1_per_thresholds.csv", index=True)
        
        df.to_csv("/home/jovyan/ChestXray-14/results/paper/table3_1/best_thresholds.csv", index=True)
        self.best_thresholds = df.copy()["thresholds"].values

    def __enter__(self):
        return self

    def __exit__(self, *arg):
        # print("Exit!")
        self.y_true = None
        self.y_preds = None
    

In [5]:
def get_test_dataset_5_fold():
    dataset = Dataset()
    _, test_dataset_fold_1 = dataset.get_kfold(fold_number=1, sample=False)
    _, test_dataset_fold_2 = dataset.get_kfold(fold_number=2, sample=False)
    _, test_dataset_fold_3 = dataset.get_kfold(fold_number=3, sample=False)
    _, test_dataset_fold_4 = dataset.get_kfold(fold_number=4, sample=False)
    _, test_dataset_fold_5 = dataset.get_kfold(fold_number=5, sample=False)
    return (
        test_dataset_fold_1,
        test_dataset_fold_2,
        test_dataset_fold_3,
        test_dataset_fold_4,
        test_dataset_fold_5
    )

In [14]:
model_path = "/home/jovyan/ChestXray-14/results/models/EfficientNetB0_None_fold_3.h5"
best_model = Evaluate(model_path)

datasets = get_test_dataset_5_fold()

best_model.get_best_threshold()
for fold, test_dataset in enumerate(datasets):
    print(f"===== Fold {fold + 1} =====")
    with best_model:
        f1_each_class = best_model.get_f1_scores(test_dataset)
        df = pd.DataFrame(f1_each_class)
        df.to_csv("/home/jovyan/ChestXray-14/results/paper/table3_with_precision_recall_f1/best_model_fold_{}.csv".format(fold+1), index=False)
        
        precision_each_class = best_model.get_precision_scores(test_dataset, new_calculate=False)
        pd.DataFrame(precision_each_class)\
            .to_csv("/home/jovyan/ChestXray-14/results/paper/table3_with_precision_recall_f1/precision/best_model_fold_{}.csv".format(fold+1), index=False)
        
        recall_each_class = best_model.get_recall_scores(test_dataset, new_calculate=False)
        pd.DataFrame(recall_each_class)\
            .to_csv("/home/jovyan/ChestXray-14/results/paper/table3_with_precision_recall_f1/recall/best_model_fold_{}.csv".format(fold+1), index=False)
        
        print(df)
    # break

1402/1402 [==============================] - 42s 29ms/step
['No Finding', 'Atelectasis', 'Consolidation', 'Infiltration', 'Pneumothorax', 'Edema', 'Emphysema', 'Fibrosis', 'Effusion', 'Pneumonia', 'Pleural_Thickening', 'Cardiomegaly', 'Nodule', 'Mass', 'Hernia']
                    thresholds   f1_most
label                                   
No Finding            0.286432  0.740660
Atelectasis           0.150754  0.340299
Consolidation         0.110553  0.207992
Infiltration          0.201005  0.386318
Pneumothorax          0.165829  0.263662
Edema                 0.145729  0.222080
Emphysema             0.105528  0.147580
Fibrosis              0.025126  0.068509
Effusion              0.246231  0.482054
Pneumonia             0.050251  0.076980
Pleural_Thickening    0.105528  0.169416
Cardiomegaly          0.216080  0.310933
Nodule                0.075377  0.145118
Mass                  0.160804  0.218792
Hernia                0.005025  0.018711
===== Fold 1 =====
1402/1402 [==========

## Random

In [72]:
TEST_SIZE = 22424

# ['No Finding', 'Atelectasis', 'Consolidation', 'Infiltration', 'Pneumothorax', 'Edema', 'Emphysema', 'Fibrosis', 'Effusion', 'Pneumonia', 'Pleural_Thickening', 'Cardiomegaly', 'Nodule', 'Mass', 'Hernia']
CLASS_PROBABILITY = [0.4265, 0.1406, 0.941, 0.817, 0.447, 0.409, 0.375, 0.330, 0.239, 0.196, 0.178, 0.163, 0.119, 0.101, 0.016]

In [16]:
np.random.seed(42)
random_preds = (np.random.uniform(size=(TEST_SIZE, 15)) <= CLASS_PROBABILITY).astype('int16')
print(random_preds)

[[1 0 1 ... 0 0 0]
 [1 0 1 ... 0 0 0]
 [0 0 1 ... 1 0 0]
 ...
 [1 0 1 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 [0 0 1 ... 0 0 0]]


In [49]:
from pathlib import Path

# Create Path for this file result runs
result_path = "/home/jovyan/ChestXray-14/results/random_compare"
Path(result_path).mkdir(parents=True, exist_ok=True)

def create_folder(path):
    Path(path).mkdir(parents=True, exist_ok=True)

In [77]:
class EvaluateRandom:
    def __init__(self, y_preds):
        self.y_true = None
        self.y_preds = y_preds
        self.best_thresholds = None
        self.thresholds_200 = None
    
    def get_y_true(self, data):
        y_true=[]
        for X,y in data:
            for label in y:
                y_true.append(label)
        y_true = tf.Variable(y_true)
        self.y_true = y_true
        return y_true

    def get_confusion_metrics(self, y_true, y_preds):
        m = tf.keras.metrics.AUC(multi_label=True)
        m.update_state(y_true, y_preds)

        thresholds = m.thresholds
        variables = m.variables
        TP = variables[0]
        TN = variables[1]
        FP = variables[2]
        FN = variables[3]
        return thresholds, TP, TN, FP, FN
    
    def get_f1_scores(self, test_dataset):
        self.y_true = self.get_y_true(test_dataset)
        
        # print(self.y_true)
        # print(self.y_preds)
        
        metric = tfa.metrics.MultiLabelConfusionMatrix(num_classes=15)
        metric.update_state(self.y_true,
                            self.y_preds)
        result = metric.result()
        
        f1_class_dict = dict()
        for idx, confusion in enumerate(result):
            label = LABELS[idx]
            TP, TN, FP, FN = (confusion[1, 1],
                              confusion[0, 0],
                              confusion[0, 1],
                              confusion[1, 0])
            f1_score = 2*TP / (2*TP + FP + FN)
            f1_class_dict[label] = [f1_score.numpy()]
        return f1_class_dict
    
    def get_precision_scores(self, test_dataset, new_calculate=True):
        if new_calculate is True:
            self.y_true = self.get_y_true(test_dataset)

        metric = tfa.metrics.MultiLabelConfusionMatrix(num_classes=15)
        metric.update_state(self.y_true,
                            self.y_preds)
        result = metric.result()
        
        precision_class_dict = dict()
        for idx, confusion in enumerate(result):
            label = LABELS[idx]
            TP, TN, FP, FN = (confusion[1, 1],
                              confusion[0, 0],
                              confusion[0, 1],
                              confusion[1, 0])
            precision = TP / (TP + FP)
            precision_class_dict[label] = [precision.numpy()]
        return precision_class_dict
    
    def get_recall_scores(self, test_dataset, new_calculate=True):
        if new_calculate is True:
            self.y_true = self.get_y_true(test_dataset)
        metric = tfa.metrics.MultiLabelConfusionMatrix(num_classes=15)
        metric.update_state(self.y_true,
                            self.y_preds)
        result = metric.result()
        
        recall_class_dict = dict()
        for idx, confusion in enumerate(result):
            label = LABELS[idx]
            TP, TN, FP, FN = (confusion[1, 1],
                              confusion[0, 0],
                              confusion[0, 1],
                              confusion[1, 0])
            recall = TP / (TP + FN)
            recall_class_dict[label] = [recall.numpy()]
        return recall_class_dict

    def __enter__(self):
        print("Runing ...")
        return self

    def __exit__(self, *arg):
        self.y_true = None
        self.y_preds = None
        print("Done !")

In [85]:
MAX_EXPERIMENT = 2
EXP_IDEX_ROUNDS = list(np.arange(MAX_EXPERIMENT * 5, step=5))

datasets = get_test_dataset_5_fold()

for start_idex in EXP_IDEX_ROUNDS:
    number_of_run = start_idex // 5 + 1
    print(f">>> Number of run: {number_of_run}")
    for seed in np.arange(start=start_idex, stop=start_idex+5):
        fold = seed % 5
        
        np.random.seed(seed)
        random_preds = (np.random.uniform(size=(TEST_SIZE, 15)) <= CLASS_PROBABILITY).astype('int16')
        
        evaluate = EvaluateRandom(random_preds)
        
        print(f"===== Random, Seed={seed}, Fold={fold + 1} =====")
        with evaluate:
            test_dataset = datasets[fold]
            
            create_folder(f"{result_path}/run_{number_of_run}/f1-score")
            create_folder(f"{result_path}/run_{number_of_run}/precision")
            create_folder(f"{result_path}/run_{number_of_run}/recall")
            
            f1_each_class = evaluate.get_f1_scores(test_dataset)
            df = pd.DataFrame(f1_each_class)
            df.to_csv(f"{result_path}/run_{number_of_run}/f1-score/random_fold_{fold+1}.csv", index=False)

            precision_each_class = evaluate.get_precision_scores(test_dataset, new_calculate=False)
            pd.DataFrame(precision_each_class)\
                .to_csv(f"{result_path}/run_{number_of_run}/precision/random_fold_{fold+1}.csv", index=False)

            recall_each_class = evaluate.get_recall_scores(test_dataset, new_calculate=False)
            pd.DataFrame(recall_each_class)\
                .to_csv(f"{result_path}/run_{number_of_run}/recall/random_fold_{fold+1}.csv", index=False)

            # print(df)

    print("====\n")
    # break

>>> Number of run: 1
===== Random, Seed=0, Fold=1 =====
Runing ...
Done !
===== Random, Seed=1, Fold=2 =====
Runing ...
Done !
===== Random, Seed=2, Fold=3 =====
Runing ...
Done !
===== Random, Seed=3, Fold=4 =====
Runing ...
Done !
===== Random, Seed=4, Fold=5 =====
Runing ...
Done !
====

>>> Number of run: 2
===== Random, Seed=5, Fold=1 =====
Runing ...
Done !
===== Random, Seed=6, Fold=2 =====
Runing ...
Done !
===== Random, Seed=7, Fold=3 =====
Runing ...
Done !
===== Random, Seed=8, Fold=4 =====
Runing ...
Done !
===== Random, Seed=9, Fold=5 =====
Runing ...
Done !
====



In [138]:
def add_to_class_dict(class_dict, key, value):
    try: 
        class_dict[key].append(value)
        # print("read")
    except KeyError:
        class_dict[key] = [value]
        # print("New")

In [152]:
import glob

for fold_num in range(1, 6):
    print(">>> Fold:", fold_num)
    files_pattern = f"{result_path}/run_*/precision/*_fold_{fold_num}.csv"
    files_path = glob.glob(files_pattern)
    
    # Read all runs on fold ...
    class_scores = {}
    for file in files_path:
        # print(file)
        df = pd.read_csv(file)
        for key, value in df.items():
            # print(key, "=", value.values[0])
            add_to_class_dict(class_scores, key, value.values[0])
    
    # Summary dict
    summary_class_scores = {}
    for key, value in class_scores.items():
        summary_class_scores[key] = [np.mean(value)]
    
    # Save to path
    summary_path = f"{result_path}/precision_fold_{fold_num}.csv"
    summary_df = pd.DataFrame(summary_class_scores)
    summary_df.to_csv(summary_path, index=False)
    
    print("Done !")
    # print(summary_df)
    # print(summary_path)
    # break

# Concat all folds


>>> Fold: 1
Done !
>>> Fold: 2
Done !
>>> Fold: 3
Done !
>>> Fold: 4
Done !
>>> Fold: 5
Done !


In [90]:
# F1-scores
path = f"{result_path}/run_*/precision/*_fold_1.csv"
for path in glob.glob(path):
    print(path)

## Evaluate 1000 Runs

In [48]:
MAX_EXPERIMENT = 1000
EXP_IDEX_ROUNDS = list(np.arange(MAX_EXPERIMENT * 5, step=5))

for start_idex in EXP_IDEX_ROUNDS:
    for seed in np.arange(start=start_idex, stop=start_idex+5):
        print(seed%5)
    print("====")
    # break

0
1
2
3
4
====
0
1
2
3
4
====
0
1
2
3
4
====
0
1
2
3
4
====
0
1
2
3
4
====
0
1
2
3
4
====
0
1
2
3
4
====
0
1
2
3
4
====
0
1
2
3
4
====
0
1
2
3
4
====
0
1
2
3
4
====
0
1
2
3
4
====
0
1
2
3
4
====
0
1
2
3
4
====
0
1
2
3
4
====
0
1
2
3
4
====
0
1
2
3
4
====
0
1
2
3
4
====
0
1
2
3
4
====
0
1
2
3
4
====
0
1
2
3
4
====
0
1
2
3
4
====
0
1
2
3
4
====
0
1
2
3
4
====
0
1
2
3
4
====
0
1
2
3
4
====
0
1
2
3
4
====
0
1
2
3
4
====
0
1
2
3
4
====
0
1
2
3
4
====
0
1
2
3
4
====
0
1
2
3
4
====
0
1
2
3
4
====
0
1
2
3
4
====
0
1
2
3
4
====
0
1
2
3
4
====
0
1
2
3
4
====
0
1
2
3
4
====
0
1
2
3
4
====
0
1
2
3
4
====
0
1
2
3
4
====
0
1
2
3
4
====
0
1
2
3
4
====
0
1
2
3
4
====
0
1
2
3
4
====
0
1
2
3
4
====
0
1
2
3
4
====
0
1
2
3
4
====
0
1
2
3
4
====
0
1
2
3
4
====
0
1
2
3
4
====
0
1
2
3
4
====
0
1
2
3
4
====
0
1
2
3
4
====
0
1
2
3
4
====
0
1
2
3
4
====
0
1
2
3
4
====
0
1
2
3
4
====
0
1
2
3
4
====
0
1
2
3
4
====
0
1
2
3
4
====
0
1
2
3
4
====
0
1
2
3
4
====
0
1
2
3
4
====
0
1
2
3
4
====
0
1
2
3
4
====
0
1
2
3
4
