In [3]:
import numpy as np
import pandas as pd
import tensorflow as tf

2022-11-01 09:31:03.049447: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.


In [8]:
def get_summary(history_path):
    folds = tf.io.gfile.glob(history_path + "*.csv")

    for idx, fold in enumerate(folds):
        train_loss = pd.read_csv(fold).iloc[:, 2]
        validatation_loss = pd.read_csv(fold).iloc[:, 4]
        train_AUC = pd.read_csv(fold).iloc[:, 1]
        validatation_AUC = pd.read_csv(fold).iloc[:, 3]
        
        best_model = validatation_loss.argmin()
        
        print("====="*4)
        print(f"Fold {idx + 1}")
        if idx == 0:
            total = np.array([train_loss[best_model], validatation_loss[best_model]])
        else:
            total = np.vstack([total, np.array([train_loss[best_model], validatation_loss[best_model]])])
            
        print("Train (loss) = {:.4f}, Validate (loss) = {:.4f}".format(train_loss[best_model], validatation_loss[best_model]))
        print("Train (AUC) = {:.4f}, Validate (AUC) = {:.4f}".format(train_AUC[best_model], validatation_AUC[best_model]))
        
    print("====="*4)
    print("Summary")
    print(total)
    print("Train (loss) = Best {:.4f}, Avg. {:.4f}, Worst {:.4f}".format(total.min(axis=0)[0], total.mean(axis=0)[0], total.max(axis=0)[0]))
    print("Validate (loss) = Best {:.4f}, Avg. {:.4f}, Worst {:.4f}".format(total.min(axis=0)[1], total.mean(axis=0)[1], total.max(axis=0)[1]))

### Exp 1

In [9]:
history_path = "results/history/DenseNet121_noDropout_None/"
get_summary(history_path)

Fold 1
Train (loss) = 0.1922, Validate (loss) = 0.1955
Train (AUC) = 0.7407, Validate (AUC) = 0.7168
Fold 2
Train (loss) = 0.1900, Validate (loss) = 0.1970
Train (AUC) = 0.7501, Validate (AUC) = 0.7235
Fold 3
Train (loss) = 0.1880, Validate (loss) = 0.1942
Train (AUC) = 0.7566, Validate (AUC) = 0.7426
Fold 4
Train (loss) = 0.1922, Validate (loss) = 0.1956
Train (AUC) = 0.7361, Validate (AUC) = 0.7323
Fold 5
Train (loss) = 0.1917, Validate (loss) = 0.1958
Train (AUC) = 0.7425, Validate (AUC) = 0.7227
Summary
[[0.19221897 0.19551492]
 [0.19003738 0.19702502]
 [0.18800645 0.19422519]
 [0.19223595 0.19559292]
 [0.19174725 0.19581158]]
Train (loss) = Best 0.1880, Avg. 0.1908, Worst 0.1922
Validate (loss) = Best 0.1942, Avg. 0.1956, Worst 0.1970


### Exp 2

In [97]:
history_path = "results/history/DenseNet121_noDropout_imagenet/"
get_summary(history_path)

Fold 1
Train (loss) = 0.1883, Validate (loss) = 0.1896
Fold 2
Train (loss) = 0.1843, Validate (loss) = 0.1922
Fold 3
Train (loss) = 0.1869, Validate (loss) = 0.1914
Fold 4
Train (loss) = 0.1910, Validate (loss) = 0.1929
Fold 5
Train (loss) = 0.1851, Validate (loss) = 0.1918
Summary
[[0.1883385  0.18962517]
 [0.18431026 0.1921898 ]
 [0.1869334  0.19141941]
 [0.19102007 0.19290455]
 [0.18508671 0.19176236]]
Train (loss) = Best 0.1843, Avg. 0.1871, Worst 0.1910
Validate (loss) = Best 0.1896, Avg. 0.1916, Worst 0.1929


### Exp 3

In [96]:
history_path = "results/history/EfficientNetB0_None/"
get_summary(history_path)

Fold 1
Train (loss) = 0.1858, Validate (loss) = 0.1884
Fold 2
Train (loss) = 0.1882, Validate (loss) = 0.1916
Fold 3
Train (loss) = 0.1855, Validate (loss) = 0.1907
Fold 4
Train (loss) = 0.1891, Validate (loss) = 0.1916
Fold 5
Train (loss) = 0.1827, Validate (loss) = 0.1925
Summary
[[0.18575522 0.18839887]
 [0.18816352 0.19157647]
 [0.1854662  0.19066538]
 [0.18906143 0.19158757]
 [0.18273166 0.19247483]]
Train (loss) = Best 0.1827, Avg. 0.1862, Worst 0.1891
Validate (loss) = Best 0.1884, Avg. 0.1909, Worst 0.1925


### Exp 4

In [99]:
history_path = "results/history/EfficientNetB0_imagenet/"
get_summary(history_path)

Fold 1
Train (loss) = 0.1793, Validate (loss) = 0.2053
Fold 2
Train (loss) = 0.1778, Validate (loss) = 0.2220
Fold 3
Train (loss) = 0.1814, Validate (loss) = 0.2135
Fold 4
Train (loss) = 0.1922, Validate (loss) = 0.2226
Fold 5
Train (loss) = 0.1732, Validate (loss) = 0.2236
Summary
[[0.17933393 0.20525976]
 [0.17778866 0.22201683]
 [0.18139541 0.21350904]
 [0.19223592 0.22257505]
 [0.17316452 0.22361067]]
Train (loss) = Best 0.1732, Avg. 0.1808, Worst 0.1922
Validate (loss) = Best 0.2053, Avg. 0.2174, Worst 0.2236


### Exp 5

In [100]:
history_path = "results/history/Resnet50_None/"
get_summary(history_path)

Fold 1
Train (loss) = 0.1943, Validate (loss) = 0.1943
Fold 2
Train (loss) = 0.1931, Validate (loss) = 0.1974
Fold 3
Train (loss) = 0.1930, Validate (loss) = 0.1955
Fold 4
Train (loss) = 0.1925, Validate (loss) = 0.1973
Fold 5
Train (loss) = 0.1967, Validate (loss) = 0.1985
Summary
[[0.19431207 0.19430895]
 [0.19307916 0.19738032]
 [0.19300176 0.19545916]
 [0.19252598 0.19734156]
 [0.19667855 0.19846098]]
Train (loss) = Best 0.1925, Avg. 0.1939, Worst 0.1967
Validate (loss) = Best 0.1943, Avg. 0.1966, Worst 0.1985


### Exp 6

In [101]:
history_path = "results/history/Resnet50_imagenet/"
get_summary(history_path)

Fold 1
Train (loss) = 0.1908, Validate (loss) = 0.1939
Fold 2
Train (loss) = 0.1892, Validate (loss) = 0.1934
Fold 3
Train (loss) = 0.1897, Validate (loss) = 0.1927
Fold 4
Train (loss) = 0.1910, Validate (loss) = 0.1954
Fold 5
Train (loss) = 0.1903, Validate (loss) = 0.1943
Summary
[[0.19076835 0.19394961]
 [0.18918039 0.19340535]
 [0.18968241 0.19267353]
 [0.19100335 0.19538164]
 [0.19028458 0.19425426]]
Train (loss) = Best 0.1892, Avg. 0.1902, Worst 0.1910
Validate (loss) = Best 0.1927, Avg. 0.1939, Worst 0.1954
