In [3]:
import numpy as np
import pandas as pd
import tensorflow as tf

2022-12-23 06:53:03.486324: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.


In [1]:
def get_summary(history_path):
    folds = tf.io.gfile.glob(history_path + "*.csv")

    for idx, fold in enumerate(folds):
        train_loss = pd.read_csv(fold).iloc[:, 2]
        validatation_loss = pd.read_csv(fold).iloc[:, 4]
        train_AUC = pd.read_csv(fold).iloc[:, 1]
        validatation_AUC = pd.read_csv(fold).iloc[:, 3]
        
        best_model = validatation_loss.argmin()
        
        print("====="*4)
        print(f"Fold {idx + 1}")
        if idx == 0:
            total = np.array([train_loss[best_model], validatation_loss[best_model]])
            total_auc = np.array([train_AUC[best_model], validatation_AUC[best_model]])
        else:
            total = np.vstack([total, np.array([train_loss[best_model], validatation_loss[best_model]])])
            total_auc = np.vstack([total_auc, np.array([train_AUC[best_model], validatation_AUC[best_model]])])
            
        print("Train (loss) = {:.4f}, Validate (loss) = {:.4f}".format(train_loss[best_model], validatation_loss[best_model]))
        print("Train (AUC) = {:.4f}, Validate (AUC) = {:.4f}".format(train_AUC[best_model], validatation_AUC[best_model]))
        
    print("====="*4)
    print("Summary")
    print(total)
    print("Train (loss) = Best {:.4f}, Avg. {:.4f}, Worst {:.4f}".format(total.min(axis=0)[0], total.mean(axis=0)[0], total.max(axis=0)[0]))
    print("Validate (loss) = Best {:.4f}, Avg. {:.4f}, Worst {:.4f}".format(total.min(axis=0)[1], total.mean(axis=0)[1], total.max(axis=0)[1]))
    
    print("====="*4)
    print("Summary AUC")
    print("[Train\tValidadtion]")
    print(total_auc)
    print("Train (AUC) = Best {:.4f}, Avg. {:.4f}, Worst {:.4f}".format(total_auc.max(axis=0)[0], total_auc.mean(axis=0)[0], total_auc.min(axis=0)[0]))
    print("Validate (AUC) = Best {:.4f}, Avg. {:.4f}, Worst {:.4f}".format(total_auc.max(axis=0)[1], total_auc.mean(axis=0)[1], total_auc.min(axis=0)[1]))

### Exp 1

In [4]:
history_path = "results/history/DenseNet121_noDropout_None/"
get_summary(history_path)

Fold 1
Train (loss) = 0.1922, Validate (loss) = 0.1955
Train (AUC) = 0.7407, Validate (AUC) = 0.7168
Fold 2
Train (loss) = 0.1900, Validate (loss) = 0.1970
Train (AUC) = 0.7501, Validate (AUC) = 0.7235
Fold 3
Train (loss) = 0.1880, Validate (loss) = 0.1942
Train (AUC) = 0.7566, Validate (AUC) = 0.7426
Fold 4
Train (loss) = 0.1922, Validate (loss) = 0.1956
Train (AUC) = 0.7361, Validate (AUC) = 0.7323
Fold 5
Train (loss) = 0.1917, Validate (loss) = 0.1958
Train (AUC) = 0.7425, Validate (AUC) = 0.7227
Summary
[[0.19221897 0.19551492]
 [0.19003738 0.19702502]
 [0.18800645 0.19422519]
 [0.19223595 0.19559292]
 [0.19174725 0.19581158]]
Train (loss) = Best 0.1880, Avg. 0.1908, Worst 0.1922
Validate (loss) = Best 0.1942, Avg. 0.1956, Worst 0.1970
Summary AUC
[Train	Validadtion]
[[0.74067479 0.71679479]
 [0.75011188 0.72346646]
 [0.75659627 0.74256063]
 [0.73610097 0.73232013]
 [0.74248821 0.72273523]]
Train (AUC) = Best 0.7566, Avg. 0.7452, Worst 0.7361
Validate (AUC) = Best 0.7426, Avg. 0.72

### Exp 2

In [5]:
history_path = "results/history/DenseNet121_noDropout_imagenet/"
get_summary(history_path)

Fold 1
Train (loss) = 0.1883, Validate (loss) = 0.1896
Train (AUC) = 0.7540, Validate (AUC) = 0.7417
Fold 2
Train (loss) = 0.1843, Validate (loss) = 0.1922
Train (AUC) = 0.7681, Validate (AUC) = 0.7446
Fold 3
Train (loss) = 0.1869, Validate (loss) = 0.1914
Train (AUC) = 0.7513, Validate (AUC) = 0.7447
Fold 4
Train (loss) = 0.1910, Validate (loss) = 0.1929
Train (AUC) = 0.7411, Validate (AUC) = 0.7416
Fold 5
Train (loss) = 0.1851, Validate (loss) = 0.1918
Train (AUC) = 0.7691, Validate (AUC) = 0.7414
Summary
[[0.1883385  0.18962517]
 [0.18431026 0.1921898 ]
 [0.1869334  0.19141941]
 [0.19102007 0.19290455]
 [0.18508671 0.19176236]]
Train (loss) = Best 0.1843, Avg. 0.1871, Worst 0.1910
Validate (loss) = Best 0.1896, Avg. 0.1916, Worst 0.1929
Summary AUC
[Train	Validadtion]
[[0.75402516 0.74168223]
 [0.7681362  0.74458587]
 [0.75126952 0.74471164]
 [0.74112755 0.7415567 ]
 [0.76910388 0.7413879 ]]
Train (AUC) = Best 0.7691, Avg. 0.7567, Worst 0.7411
Validate (AUC) = Best 0.7447, Avg. 0.74

### Exp 3

In [6]:
history_path = "results/history/EfficientNetB0_None/"
get_summary(history_path)

Fold 1
Train (loss) = 0.1858, Validate (loss) = 0.1884
Train (AUC) = 0.7643, Validate (AUC) = 0.7435
Fold 2
Train (loss) = 0.1882, Validate (loss) = 0.1916
Train (AUC) = 0.7528, Validate (AUC) = 0.7409
Fold 3
Train (loss) = 0.1855, Validate (loss) = 0.1907
Train (AUC) = 0.7677, Validate (AUC) = 0.7506
Fold 4
Train (loss) = 0.1891, Validate (loss) = 0.1916
Train (AUC) = 0.7470, Validate (AUC) = 0.7431
Fold 5
Train (loss) = 0.1827, Validate (loss) = 0.1925
Train (AUC) = 0.7777, Validate (AUC) = 0.7380
Summary
[[0.18575522 0.18839887]
 [0.18816352 0.19157647]
 [0.1854662  0.19066538]
 [0.18906143 0.19158757]
 [0.18273166 0.19247483]]
Train (loss) = Best 0.1827, Avg. 0.1862, Worst 0.1891
Validate (loss) = Best 0.1884, Avg. 0.1909, Worst 0.1925
Summary AUC
[Train	Validadtion]
[[0.76426971 0.74345529]
 [0.75277746 0.74091911]
 [0.76772487 0.75063926]
 [0.74699622 0.74308687]
 [0.77770668 0.73802781]]
Train (AUC) = Best 0.7777, Avg. 0.7619, Worst 0.7470
Validate (AUC) = Best 0.7506, Avg. 0.74

### Exp 4

In [7]:
history_path = "results/history/EfficientNetB0_imagenet/"
get_summary(history_path)

Fold 1
Train (loss) = 0.1793, Validate (loss) = 0.2053
Train (AUC) = 0.7882, Validate (AUC) = 0.6802
Fold 2
Train (loss) = 0.1778, Validate (loss) = 0.2220
Train (AUC) = 0.7872, Validate (AUC) = 0.4931
Fold 3
Train (loss) = 0.1814, Validate (loss) = 0.2135
Train (AUC) = 0.7768, Validate (AUC) = 0.6267
Fold 4
Train (loss) = 0.1922, Validate (loss) = 0.2226
Train (AUC) = 0.7272, Validate (AUC) = 0.5487
Fold 5
Train (loss) = 0.1732, Validate (loss) = 0.2236
Train (AUC) = 0.8078, Validate (AUC) = 0.6151
Summary
[[0.17933393 0.20525976]
 [0.17778866 0.22201683]
 [0.18139541 0.21350904]
 [0.19223592 0.22257505]
 [0.17316452 0.22361067]]
Train (loss) = Best 0.1732, Avg. 0.1808, Worst 0.1922
Validate (loss) = Best 0.2053, Avg. 0.2174, Worst 0.2236
Summary AUC
[Train	Validadtion]
[[0.78823811 0.68020892]
 [0.78724372 0.49314421]
 [0.77683371 0.62669975]
 [0.72724903 0.54871154]
 [0.80781823 0.61508071]]
Train (AUC) = Best 0.8078, Avg. 0.7775, Worst 0.7272
Validate (AUC) = Best 0.6802, Avg. 0.59

### Exp 5

In [8]:
history_path = "results/history/Resnet50_None/"
get_summary(history_path)

Fold 1
Train (loss) = 0.1943, Validate (loss) = 0.1943
Train (AUC) = 0.7290, Validate (AUC) = 0.7189
Fold 2
Train (loss) = 0.1931, Validate (loss) = 0.1974
Train (AUC) = 0.7241, Validate (AUC) = 0.7165
Fold 3
Train (loss) = 0.1930, Validate (loss) = 0.1955
Train (AUC) = 0.7251, Validate (AUC) = 0.7255
Fold 4
Train (loss) = 0.1925, Validate (loss) = 0.1973
Train (AUC) = 0.7355, Validate (AUC) = 0.7192
Fold 5
Train (loss) = 0.1967, Validate (loss) = 0.1985
Train (AUC) = 0.7117, Validate (AUC) = 0.7044
Summary
[[0.19431207 0.19430895]
 [0.19307916 0.19738032]
 [0.19300176 0.19545916]
 [0.19252598 0.19734156]
 [0.19667855 0.19846098]]
Train (loss) = Best 0.1925, Avg. 0.1939, Worst 0.1967
Validate (loss) = Best 0.1943, Avg. 0.1966, Worst 0.1985
Summary AUC
[Train	Validadtion]
[[0.72897798 0.71888655]
 [0.72414422 0.71645623]
 [0.72511858 0.72546518]
 [0.7354508  0.71921253]
 [0.7116816  0.70436263]]
Train (AUC) = Best 0.7355, Avg. 0.7251, Worst 0.7117
Validate (AUC) = Best 0.7255, Avg. 0.71

### Exp 6

In [9]:
history_path = "results/history/Resnet50_imagenet/"
get_summary(history_path)

Fold 1
Train (loss) = 0.1908, Validate (loss) = 0.1939
Train (AUC) = 0.7403, Validate (AUC) = 0.7306
Fold 2
Train (loss) = 0.1892, Validate (loss) = 0.1934
Train (AUC) = 0.7507, Validate (AUC) = 0.7403
Fold 3
Train (loss) = 0.1897, Validate (loss) = 0.1927
Train (AUC) = 0.7426, Validate (AUC) = 0.7431
Fold 4
Train (loss) = 0.1910, Validate (loss) = 0.1954
Train (AUC) = 0.7351, Validate (AUC) = 0.7356
Fold 5
Train (loss) = 0.1903, Validate (loss) = 0.1943
Train (AUC) = 0.7419, Validate (AUC) = 0.7231
Summary
[[0.19076835 0.19394961]
 [0.18918039 0.19340535]
 [0.18968241 0.19267353]
 [0.19100335 0.19538164]
 [0.19028458 0.19425426]]
Train (loss) = Best 0.1892, Avg. 0.1902, Worst 0.1910
Validate (loss) = Best 0.1927, Avg. 0.1939, Worst 0.1954
Summary AUC
[Train	Validadtion]
[[0.7402615  0.73057485]
 [0.75067532 0.74030495]
 [0.74257964 0.7430563 ]
 [0.73506951 0.73558921]
 [0.74191457 0.72307956]]
Train (AUC) = Best 0.7507, Avg. 0.7421, Worst 0.7351
Validate (AUC) = Best 0.7431, Avg. 0.73