In [19]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [94]:
def get_summary(history_path):
    folds = tf.io.gfile.glob(history_path + "*.csv")

    for idx, fold in enumerate(folds):
        train = pd.read_csv(fold).iloc[:, 2]
        validate = pd.read_csv(fold).iloc[:, 4]
        best_model = validate.argmin()
        print("====="*4)
        print(f"Fold {idx + 1}")
        if idx == 0:
            total = np.array([train[best_model], validate[best_model]])
        else:
            total = np.vstack([total, np.array([train[best_model], validate[best_model]])])
            
        print("Train (loss) = {:.4f}, Validate (loss) = {:.4f}".format(train[best_model], validate[best_model]))
        
    print("====="*4)
    print("Summary")
    print(total)
    print("Train (loss) = Best {:.4f}, Avg. {:.4f}, Worst {:.4f}".format(total.min(axis=0)[0], total.mean(axis=0)[0], total.max(axis=0)[0]))
    print("Validate (loss) = Best {:.4f}, Avg. {:.4f}, Worst {:.4f}".format(total.min(axis=0)[1], total.mean(axis=0)[1], total.max(axis=0)[1]))

### Exp 1

In [98]:
history_path = "results/history/DenseNet121_Dropout_imagenet/"
get_summary(history_path)

Fold 1
Train (loss) = 0.2026, Validate (loss) = 0.2063
Fold 2
Train (loss) = 0.2174, Validate (loss) = 0.2180
Fold 3
Train (loss) = 0.2173, Validate (loss) = 0.2176
Fold 4
Train (loss) = 0.1979, Validate (loss) = 0.2051
Fold 5
Train (loss) = 0.2010, Validate (loss) = 0.2038
Summary
[[0.20262921 0.20633428]
 [0.21735357 0.21798877]
 [0.21732065 0.21756285]
 [0.19788447 0.20506634]
 [0.20097958 0.20382269]]
Train (loss) = Best 0.1979, Avg. 0.2072, Worst 0.2174
Validate (loss) = Best 0.2038, Avg. 0.2102, Worst 0.2180


### Exp 2

In [97]:
history_path = "results/history/DenseNet121_noDropout_imagenet/"
get_summary(history_path)

Fold 1
Train (loss) = 0.1883, Validate (loss) = 0.1896
Fold 2
Train (loss) = 0.1843, Validate (loss) = 0.1922
Fold 3
Train (loss) = 0.1869, Validate (loss) = 0.1914
Fold 4
Train (loss) = 0.1910, Validate (loss) = 0.1929
Fold 5
Train (loss) = 0.1851, Validate (loss) = 0.1918
Summary
[[0.1883385  0.18962517]
 [0.18431026 0.1921898 ]
 [0.1869334  0.19141941]
 [0.19102007 0.19290455]
 [0.18508671 0.19176236]]
Train (loss) = Best 0.1843, Avg. 0.1871, Worst 0.1910
Validate (loss) = Best 0.1896, Avg. 0.1916, Worst 0.1929


### Exp 3

In [96]:
history_path = "results/history/EfficientNetB0_None/"
get_summary(history_path)

Fold 1
Train (loss) = 0.1858, Validate (loss) = 0.1884
Fold 2
Train (loss) = 0.1882, Validate (loss) = 0.1916
Fold 3
Train (loss) = 0.1855, Validate (loss) = 0.1907
Fold 4
Train (loss) = 0.1891, Validate (loss) = 0.1916
Fold 5
Train (loss) = 0.1827, Validate (loss) = 0.1925
Summary
[[0.18575522 0.18839887]
 [0.18816352 0.19157647]
 [0.1854662  0.19066538]
 [0.18906143 0.19158757]
 [0.18273166 0.19247483]]
Train (loss) = Best 0.1827, Avg. 0.1862, Worst 0.1891
Validate (loss) = Best 0.1884, Avg. 0.1909, Worst 0.1925


### Exp 4

In [99]:
history_path = "results/history/EfficientNetB0_imagenet/"
get_summary(history_path)

Fold 1
Train (loss) = 0.1793, Validate (loss) = 0.2053
Fold 2
Train (loss) = 0.1778, Validate (loss) = 0.2220
Fold 3
Train (loss) = 0.1814, Validate (loss) = 0.2135
Fold 4
Train (loss) = 0.1922, Validate (loss) = 0.2226
Fold 5
Train (loss) = 0.1732, Validate (loss) = 0.2236
Summary
[[0.17933393 0.20525976]
 [0.17778866 0.22201683]
 [0.18139541 0.21350904]
 [0.19223592 0.22257505]
 [0.17316452 0.22361067]]
Train (loss) = Best 0.1732, Avg. 0.1808, Worst 0.1922
Validate (loss) = Best 0.2053, Avg. 0.2174, Worst 0.2236


### Exp 5

In [100]:
history_path = "results/history/Resnet50_None/"
get_summary(history_path)

Fold 1
Train (loss) = 0.1943, Validate (loss) = 0.1943
Fold 2
Train (loss) = 0.1931, Validate (loss) = 0.1974
Fold 3
Train (loss) = 0.1930, Validate (loss) = 0.1955
Fold 4
Train (loss) = 0.1925, Validate (loss) = 0.1973
Fold 5
Train (loss) = 0.1967, Validate (loss) = 0.1985
Summary
[[0.19431207 0.19430895]
 [0.19307916 0.19738032]
 [0.19300176 0.19545916]
 [0.19252598 0.19734156]
 [0.19667855 0.19846098]]
Train (loss) = Best 0.1925, Avg. 0.1939, Worst 0.1967
Validate (loss) = Best 0.1943, Avg. 0.1966, Worst 0.1985


### Exp 6

In [101]:
history_path = "results/history/Resnet50_imagenet/"
get_summary(history_path)

Fold 1
Train (loss) = 0.1908, Validate (loss) = 0.1939
Fold 2
Train (loss) = 0.1892, Validate (loss) = 0.1934
Fold 3
Train (loss) = 0.1897, Validate (loss) = 0.1927
Fold 4
Train (loss) = 0.1910, Validate (loss) = 0.1954
Fold 5
Train (loss) = 0.1903, Validate (loss) = 0.1943
Summary
[[0.19076835 0.19394961]
 [0.18918039 0.19340535]
 [0.18968241 0.19267353]
 [0.19100335 0.19538164]
 [0.19028458 0.19425426]]
Train (loss) = Best 0.1892, Avg. 0.1902, Worst 0.1910
Validate (loss) = Best 0.1927, Avg. 0.1939, Worst 0.1954
